name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    branches-ignore:
      - "dependabot/*"
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          addAssignees: true
          addReviewers: true
          reviewers: |
            zhilyaev
            r3nic1e
          numberOfReviewers: 1
