name: Go lint

on:
  push:
    paths:
      - "**.go"
      - .github/workflows/go-lint.yml
      - .golangci.yml

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
