name: Go lint

on:
  push:
    paths:
      - "**.go"
      - .github/workflows/go-lint.yml
      - .golangci.yml

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.59.0
