name: Go Test

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.go"
  push:
    branches:
      - main
    paths:
      - "**.go"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Create KinD cluster
        uses: container-tools/kind-action@v2
        with:
          registry: false

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install go modules
        run: go mod download

      - name: Run tests
        run: go test -coverprofile=./tests.cov -v -covermode=atomic -timeout=20m --tags=integration ./...

      - uses: codecov/codecov-action@v4
        with:
          files: ./tests.cov
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
