name: Test GoReleaser config

on:
  pull_request:
    branches:
      - main
    paths:
      - ".goreleaser.yml"

jobs:
  goreleaser:
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: check

  goreleaser-test:
    runs-on: macos-latest
    permissions:
      contents: write # to create release
      issues: write # to close milestone
      packages: write # to upload package
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --skip-validate --clean --skip-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.CR_PAT }}
          TELEGRAM_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Generate schema.json
        run: ./dist/helmwave_darwin_amd64_v1/helmwave schema > schema.json
